CREATE TABLE IF NOT EXISTS `enrollments` (
  `id` int AUTO_INCREMENT NOT NULL,
  `source` enum('kai','form','staff') NOT NULL DEFAULT 'form',
  `status` enum('draft','submitted','approved','rejected') NOT NULL DEFAULT 'draft',
  `firstName` varchar(255) NOT NULL,
  `lastName` varchar(255) NOT NULL,
  `dateOfBirth` timestamp,
  `age` int,
  `phone` varchar(20),
  `email` varchar(320),
  `streetAddress` varchar(255),
  `city` varchar(100),
  `state` varchar(50),
  `zipCode` varchar(20),
  `guardianName` varchar(255),
  `guardianRelationship` varchar(50),
  `guardianPhone` varchar(20),
  `guardianEmail` varchar(320),
  `programInterest` varchar(100),
  `experienceLevel` enum('beginner','intermediate','advanced') DEFAULT 'beginner',
  `classType` varchar(100),
  `goals` text,
  `motivation` text,
  `allergies` text,
  `medicalConditions` text,
  `emergencyContactName` varchar(255),
  `emergencyContactPhone` varchar(20),
  `selectedMembershipPlan` varchar(100),
  `pricingNotes` text,
  `waiverSigned` int NOT NULL DEFAULT 0,
  `waiverSignature` text,
  `waiverSignedAt` timestamp,
  `consentGiven` int NOT NULL DEFAULT 0,
  `conversationId` int,
  `conversationTranscript` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `submittedAt` timestamp,
  CONSTRAINT `enrollments_id` PRIMARY KEY(`id`)
);
