CREATE TABLE `dojo_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`schoolName` varchar(255),
	`contactEmail` varchar(320),
	`contactPhone` varchar(20),
	`website` varchar(500),
	`timezone` varchar(100) DEFAULT 'America/New_York',
	`instructorTitle` varchar(50),
	`instructorFirstName` varchar(255),
	`instructorLastName` varchar(255),
	`martialArtsStyle` varchar(100),
	`addressLine1` varchar(255),
	`addressLine2` varchar(255),
	`city` varchar(100),
	`state` varchar(100),
	`zipCode` varchar(20),
	`country` varchar(100) DEFAULT 'United States',
	`weatherApiKey` varchar(255),
	`enableWeatherAlerts` int DEFAULT 1,
	`hasOutdoorClasses` int DEFAULT 0,
	`heatIndexThreshold` int DEFAULT 95,
	`airQualityThreshold` int DEFAULT 150,
	`paymentProvider` varchar(50),
	`stripeApiKey` varchar(255),
	`stripePublishableKey` varchar(255),
	`stripeWebhookSecret` varchar(255),
	`squareAccessToken` varchar(255),
	`squareLocationId` varchar(255),
	`setupCompleted` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dojo_settings_id` PRIMARY KEY(`id`)
);
