CREATE TABLE `billing_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`provider` enum('pcbancard','stripe') NOT NULL,
	`status` enum('draft','submitted','under_review','approved','rejected','requires_info') NOT NULL DEFAULT 'draft',
	`businessName` varchar(255),
	`dbaName` varchar(255),
	`businessAddress` text,
	`businessPhone` varchar(20),
	`ownerName` varchar(255),
	`ownerCell` varchar(20),
	`managerName` varchar(255),
	`managerCell` varchar(20),
	`hoursOfOperation` varchar(255),
	`daysOfOperation` varchar(255),
	`estimatedMonthlyVolume` int,
	`specialInstructions` text,
	`pcbancardRepName` varchar(255) DEFAULT 'Randy Sinclair',
	`pcbancardRepPhone` varchar(20) DEFAULT '682-218-1669',
	`stripeAccountId` varchar(255),
	`stripeOnboardingComplete` int DEFAULT 0,
	`submittedAt` timestamp,
	`reviewedAt` timestamp,
	`approvedAt` timestamp,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`documentType` enum('drivers_license','voided_check','state_ein','address_verification','bank_letter') NOT NULL,
	`s3Key` varchar(500) NOT NULL,
	`s3Url` varchar(1000) NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileSize` int,
	`mimeType` varchar(100),
	`verified` int NOT NULL DEFAULT 0,
	`verifiedAt` timestamp,
	`verifiedBy` int,
	`verificationNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `billing_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` varchar(255) NOT NULL,
	`paymentMethodId` int NOT NULL,
	`studentId` int,
	`customerName` varchar(255),
	`customerEmail` varchar(320),
	`amount` int NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`status` enum('pending','completed','failed','refunded','disputed') NOT NULL DEFAULT 'pending',
	`cardLast4` varchar(4),
	`cardBrand` varchar(50),
	`programId` int,
	`invoiceId` int,
	`processorResponse` text,
	`errorMessage` text,
	`processedAt` timestamp,
	`refundedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `billing_transactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `billing_transactions_transactionId_unique` UNIQUE(`transactionId`)
);
--> statement-breakpoint
CREATE TABLE `payment_methods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider` enum('pcbancard','stripe','square','other') NOT NULL,
	`providerName` varchar(255),
	`merchantId` varchar(255),
	`apiKey` varchar(500),
	`apiSecret` varchar(500),
	`webhookSecret` varchar(500),
	`isActive` int NOT NULL DEFAULT 0,
	`isPrimary` int NOT NULL DEFAULT 0,
	`applicationId` int,
	`acceptedCardTypes` text,
	`transactionFeePercent` int,
	`transactionFeeFixed` int,
	`isTestMode` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_methods_id` PRIMARY KEY(`id`)
);
