CREATE TABLE `documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerType` enum('student','guardian','staff','account') NOT NULL,
	`ownerId` int NOT NULL,
	`linkedStudentId` int,
	`threadId` int,
	`messageId` int,
	`source` enum('chat_upload','waiver','invoice','onboarding','manual_upload','receipt') NOT NULL,
	`filename` varchar(500) NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`sizeBytes` int NOT NULL,
	`storageUrl` varchar(1000) NOT NULL,
	`tags` text,
	`permissions` text,
	`description` text,
	`uploadedById` int,
	`uploadedByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documents_id` PRIMARY KEY(`id`)
);
